version: "2"

services:
  minidlna:
    image: felipeconti/rpi-minidlna
    network_mode: "host"
    ports:
      - "8200:8200"
      - "1900:1900"
      - "41911:41911"
      - "55654:55654"
    volumes:
      - ~/Downloads:/data
#    networks:
#      - movies
  deluge:
    image: felipeconti/rpi-deluge
    network_mode: "host"
    volumes:
      - ~/Downloads:/data
    ports:
      - "8112:8112"
      - "58846:58846"
#    networks:
#      - movies

#networks:
#  movies:
##    driver: host
#    external:
#      name: host
